# Generated by Django 4.2.5 on 2023-09-30 07:52

import django.core.validators
from django.db import migrations, models
import userdatamanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default=('L', 'Laki-Laki'), max_length=2)),
                ('NIK', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('alamat', models.CharField(max_length=200)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(verbose_name='tanggal lahir')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('no_telepon', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('tahun_masuk', models.PositiveIntegerField(default=2023)),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default=('L', 'Laki-Laki'), max_length=2)),
                ('NIK', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('alamat', models.CharField(max_length=200)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(verbose_name='tanggal lahir')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('no_telepon', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('tahun_masuk', models.PositiveIntegerField(default=2023)),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default=('L', 'Laki-Laki'), max_length=2)),
                ('NIK', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('NIS', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('NISN', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('alamat', models.CharField(max_length=200)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(verbose_name='tanggal lahir')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('no_telepon', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('nama_ayah_kandung', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('nama_ibu_kandung', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('tahun_masuk', models.PositiveIntegerField(default=2023)),
                ('tahun_keluar', models.PositiveIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(null=True, upload_to=userdatamanagement.models.rename_uploaded_image)),
                ('nama_wali', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')])),
                ('jenis_kelamin_wali', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default=('L', 'Laki-Laki'), max_length=2)),
                ('NIK_wali', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('alamat_wali', models.CharField(max_length=200)),
                ('tempat_lahir_wali', models.CharField(max_length=100)),
                ('tanggal_lahir_wali', models.DateField(verbose_name='tanggal lahir wali')),
                ('email_wali', models.CharField(max_length=50, unique=True)),
                ('no_telepon_wali', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
            ],
            options={
                'ordering': ('nama',),
            },
        ),
    ]
